version: 3
useFMTitle: true
useNoteTitleForLink: true
noLegacyNoteRef: true
mermaid: true
useKatex: true
dev:
    enablePreviewV2: true
site:
    copyAssets: true
    siteHierarchies:
        - root
    siteRootDir: docs
    duplicateNoteBehavior:
        action: useVault
        payload:
            - vault
    logo: vault/assets/images/logo.png
    siteFaviconPath: vault/assets/images/favicon.ico
    usePrettyRefs: true
    assetsPrefix: /dendron-notes
    siteUrl: 'https://angelarwang.com'
    githubCname: angelarwang.com
    gh_edit_link: true
    gh_edit_repository: 'https://github.com/angelarw/dendron-notes'
    gh_edit_link_text: Edit this page on GitHub
    gh_edit_branch: gh-pages
    gh_edit_view_mode: edit
    gh_root: docs/
    siteLastModified: true
    title: Angela's note universe
    description: >-
        This is where I keep and share my notes on books, tech, travel, and
        other hobbies :)
    twitter:
        card: summary
        username: angelaw_ruohan
    author:
        name: Angela Ruohan Wang
commands:
    lookup:
        note:
            selectionMode: extract
            confirmVaultOnCreate: false
            leaveTrace: false
    insertNote:
        initialValue: templates
    insertNoteLink:
        aliasMode: none
        enableMultiSelect: false
    insertNoteIndex:
        enableMarker: false
    randomNote: {}
workspace:
    dendronVersion: 0.66.1
    vaults:
        -
            fsPath: vault
    journal:
        dailyDomain: daily
        name: journal
        dateFormat: y.MM.dd
        addBehavior: childOfDomain
    scratch:
        name: scratch
        dateFormat: y.MM.dd.HHmmss
        addBehavior: asOwnDomain
    graph:
        zoomSpeed: 1
    enableAutoCreateOnDefinition: false
    enableXVaultWikiLink: false
    enableRemoteVaultInit: true
    workspaceVaultSyncMode: noCommit
    enableAutoFoldFrontmatter: true
    maxPreviewsCached: 10
    maxNoteLength: 204800
    task:
        name: ''
        dateFormat: ''
        addBehavior: childOfCurrent
        statusSymbols:
            '': ' '
            wip: w
            done: x
            assigned: a
            moved: m
            blocked: b
            delegated: l
            dropped: d
            pending: 'y'
        prioritySymbols:
            H: high
            M: medium
            L: low
        todoIntegration: false
        createTaskSelectionType: selection2link
    enableUserTags: true
    enableHashTags: true
usePrettyRefs: true
