# uncomment to preview locally
#theme: "just-the-docs"
remote_theme: dendronhq/dendron-jekyll
title: Dendron
logo: "/assets/images/logo.png"
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "*/dendron.template.release.md"
]
footer_content: ""

gh_edit_link: false

# seo
tagline: "Angelarw's note universe"
description: "This is where I keep and share my notes on books, tech, travel, and other hobbies :)"
twitter:
  card: summary
  username: dendronhq
author:
  twitter: dendronhq

defaults:
  -
    scope:
      path: "notes" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/images/logo.png"
