# uncomment to preview locally
#theme: "dendron-jekyll"
remote_theme: dendronhq/dendron-jekyll
title: Angela's note universe
logo: "/assets/images/logo.png"
exclude: [ "node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", "*/dendron.template.release.md"
]
footer_content: ""
markdown: kramdown
enable_mathjax: true
kramdown:
  math_engine: mathjax
url: "https://angelarwang.com"

gh_edit_link: true 
gh_edit_repository: "https://github.com/angelarw/dendron-notes"
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_view_mode: "tree" # or "edit" if you want the user to jump into the editor immediately
dendron_vault_path: "vault"

# seo
tagline: "Angela's note universe"
description: "This is where I keep and share my notes on books, tech, travel, and other hobbies :)"
twitter:
  card: summary
  username: angelaw_ruohan
author:
  name: "Angela Ruohan Wang"

defaults:
  -
    scope:
      path: "notes" # an empty string here means all files in the project
    values:
      layout: "default"
      image: "/assets/images/logo.png"
